spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/newnoise
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
server:
  error:
    include-message: always
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
